[Ready] lab1 - Tinyakov
makometr/ADS-9304 pull request #1
Opened 2020-09-22 10:45 UTC by mirrin00

2020-09-26 17:38 UTC, makometr requested changes
А если нужно будет в класс analyzer передавать отдельно строки или потоки? Лучше, конечно, реализовать дополнительно анализ отдельной строки (нужно). Передаваться будет const string&. (для фулл балла)

В отчёте съехала фамилия преподавателя, вывод расписать поподробнее, добавить тестов в отчёт (для фулл-балла)

2020-09-26 17:38 UTC, makometr commented on Tinyakov/lab1/Source/lab1.cpp
> +    ReaderWriter(const char* input_filename, const char* output_filename){
Почитай про string_view. Здесь не необходимо, но достойная замена для уб-ого const char*

2020-09-26 17:38 UTC, makometr commented on Tinyakov/lab1/Source/lab1.cpp
> +    ~Analyzer(){}
~Analyzer() = default;

2020-09-27 14:27 UTC, mirrin00 commented on Tinyakov/lab1/Source/lab1.cpp
> +    ~Analyzer(){}
Исправлено

2020-09-27 14:29 UTC, mirrin00 commented on Tinyakov/lab1/Source/lab1.cpp
> +    ReaderWriter(const char* input_filename, const char* output_filename){
Класс ReaderWriter был немного переделан. Теперь в методе WriteString аргумент типа string_view

2020-10-04 14:55 UTC, makometr commented
Отчёт не соответстует базовым требованиям, код в требуемых местах не улулчшен, описание тестов в отчёте отсутвует.

Оценка ухудшена, к защите работа не допкущена

2020-10-09 20:43 UTC, makometr requested changes
Удалить лишние файлы с репозитрия, поменять фамилию преподвателя, улучшить тесты

2020-10-12 09:29 UTC, merged